import type { Ref } from "./core/signals.js";
import type { VNode } from "./core/vnode.js";

export type { VNode } from "./core/vnode.js";
export { Fragment, jsx, jsxs } from "./core/vnode.js";

declare global {
	namespace JSX {
		type Element = import("./core/vnode.js").VNode;
		interface IntrinsicAttributes {
			children?: unknown;
			ref?: (el: HTMLElement | SVGElement) => void;
		}
		interface HTMLAttributes extends IntrinsicAttributes {
			class?: string | object;
			style?: string | object;
			id?: string;
			title?: string;
			lang?: string;
			dir?: "ltr" | "rtl" | "auto";
			hidden?: boolean;
			tabindex?: number;
			accesskey?: string;
			draggable?: boolean;
			contenteditable?: boolean | "plaintext-only";
			spellcheck?: boolean;
			translate?: "yes" | "no";
			role?: string;
			slot?: string;
			enterkeyhint?: string;
			inputmode?: string;
			autocapitalize?: string;
			autocorrect?: string;
			autofocus?: boolean;
			inert?: boolean;
			nonce?: string;
			part?: string;
			exportparts?: string;
			popover?: boolean | "auto" | "manual";
			writingsuggestions?: boolean;
			virtualkeyboardpolicy?: "auto" | "manual";
			is?: string;
			itemid?: string;
			itemprop?: string;
			itemref?: string;
			itemscope?: boolean;
			itemtype?: string;
			onabort?: string | ((e: Event) => void);
			onanimationcancel?: string | ((e: AnimationEvent) => void);
			onanimationend?: string | ((e: AnimationEvent) => void);
			onanimationiteration?: string | ((e: AnimationEvent) => void);
			onanimationstart?: string | ((e: AnimationEvent) => void);
			onauxclick?: string | ((e: MouseEvent) => void);
			onbeforeinput?: string | ((e: InputEvent) => void);
			onbeforematch?: string | ((e: Event) => void);
			onbeforetoggle?: string | ((e: Event) => void);
			onblur?: string | ((e: FocusEvent) => void);
			oncancel?: string | ((e: Event) => void);
			oncanplay?: string | ((e: Event) => void);
			oncanplaythrough?: string | ((e: Event) => void);
			onchange?: string | ((e: Event) => void);
			onclick?: string | ((e: MouseEvent) => void);
			onclose?: string | ((e: Event) => void);
			oncommand?: string | ((e: Event) => void);
			oncontentvisibilityautostatechange?: string | ((e: Event) => void);
			oncontextlost?: string | ((e: Event) => void);
			oncontextmenu?: string | ((e: MouseEvent) => void);
			oncontextrestored?: string | ((e: Event) => void);
			oncopy?: string | ((e: ClipboardEvent) => void);
			oncuechange?: string | ((e: Event) => void);
			oncut?: string | ((e: ClipboardEvent) => void);
			ondblclick?: string | ((e: MouseEvent) => void);
			ondrag?: string | ((e: DragEvent) => void);
			ondragend?: string | ((e: DragEvent) => void);
			ondragenter?: string | ((e: DragEvent) => void);
			ondragleave?: string | ((e: DragEvent) => void);
			ondragover?: string | ((e: DragEvent) => void);
			ondragstart?: string | ((e: DragEvent) => void);
			ondrop?: string | ((e: DragEvent) => void);
			ondurationchange?: string | ((e: Event) => void);
			onemptied?: string | ((e: Event) => void);
			onended?: string | ((e: Event) => void);
			onerror?: string | ((e: Event) => void);
			onfocus?: string | ((e: FocusEvent) => void);
			onfocusin?: string | ((e: FocusEvent) => void);
			onfocusout?: string | ((e: FocusEvent) => void);
			onformdata?: string | ((e: Event) => void);
			onfullscreenchange?: string | ((e: Event) => void);
			onfullscreenerror?: string | ((e: Event) => void);
			ongotpointercapture?: string | ((e: PointerEvent) => void);
			oninput?: string | ((e: Event) => void);
			oninvalid?: string | ((e: Event) => void);
			onkeydown?: string | ((e: KeyboardEvent) => void);
			onkeyup?: string | ((e: KeyboardEvent) => void);
			onkeypress?: string | ((e: KeyboardEvent) => void);
			onload?: string | ((e: Event) => void);
			onloadeddata?: string | ((e: Event) => void);
			onloadedmetadata?: string | ((e: Event) => void);
			onloadstart?: string | ((e: Event) => void);
			onlostpointercapture?: string | ((e: PointerEvent) => void);
			onmousedown?: string | ((e: MouseEvent) => void);
			onmouseenter?: string | ((e: MouseEvent) => void);
			onmouseleave?: string | ((e: MouseEvent) => void);
			onmousemove?: string | ((e: MouseEvent) => void);
			onmouseout?: string | ((e: MouseEvent) => void);
			onmouseover?: string | ((e: MouseEvent) => void);
			onmouseup?: string | ((e: MouseEvent) => void);
			onpaste?: string | ((e: ClipboardEvent) => void);
			onpause?: string | ((e: Event) => void);
			onplay?: string | ((e: Event) => void);
			onplaying?: string | ((e: Event) => void);
			onpointercancel?: string | ((e: PointerEvent) => void);
			onpointerdown?: string | ((e: PointerEvent) => void);
			onpointerenter?: string | ((e: PointerEvent) => void);
			onpointerleave?: string | ((e: PointerEvent) => void);
			onpointermove?: string | ((e: PointerEvent) => void);
			onpointerout?: string | ((e: PointerEvent) => void);
			onpointerover?: string | ((e: PointerEvent) => void);
			onpointerrawupdate?: string | ((e: PointerEvent) => void);
			onpointerup?: string | ((e: PointerEvent) => void);
			onprogress?: string | ((e: Event) => void);
			onratechange?: string | ((e: Event) => void);
			onreset?: string | ((e: Event) => void);
			onresize?: string | ((e: Event) => void);
			onscroll?: string | ((e: Event) => void);
			onscrollend?: string | ((e: Event) => void);
			onsecuritypolicyviolation?: string | ((e: Event) => void);
			onseeked?: string | ((e: Event) => void);
			onseeking?: string | ((e: Event) => void);
			onselect?: string | ((e: Event) => void);
			onselectionchange?: string | ((e: Event) => void);
			onselectstart?: string | ((e: Event) => void);
			onslotchange?: string | ((e: Event) => void);
			onstalled?: string | ((e: Event) => void);
			onsubmit?: string | ((e: Event) => void);
			onsuspend?: string | ((e: Event) => void);
			ontimeupdate?: string | ((e: Event) => void);
			ontoggle?: string | ((e: Event) => void);
			ontouchcancel?: string | ((e: TouchEvent) => void);
			ontouchend?: string | ((e: TouchEvent) => void);
			ontouchmove?: string | ((e: TouchEvent) => void);
			ontouchstart?: string | ((e: TouchEvent) => void);
			ontransitioncancel?: string | ((e: TransitionEvent) => void);
			ontransitionend?: string | ((e: TransitionEvent) => void);
			ontransitionrun?: string | ((e: TransitionEvent) => void);
			ontransitionstart?: string | ((e: TransitionEvent) => void);
			onvolumechange?: string | ((e: Event) => void);
			onwaiting?: string | ((e: Event) => void);
			onwheel?: string | ((e: WheelEvent) => void);
		}
		interface IntrinsicElements {
			html: HTMLAttributes & { lang?: string };
			head: HTMLAttributes;
			body: HTMLAttributes;
			base: HTMLAttributes & { href?: string; target?: string };
			title: HTMLAttributes;
			div: HTMLAttributes;
			span: HTMLAttributes;
			p: HTMLAttributes;
			h1: HTMLAttributes;
			h2: HTMLAttributes;
			h3: HTMLAttributes;
			h4: HTMLAttributes;
			h5: HTMLAttributes;
			h6: HTMLAttributes;
			hgroup: HTMLAttributes;
			section: HTMLAttributes;
			article: HTMLAttributes;
			aside: HTMLAttributes;
			header: HTMLAttributes;
			footer: HTMLAttributes;
			nav: HTMLAttributes;
			main: HTMLAttributes;
			address: HTMLAttributes;
			search: HTMLAttributes;
			ul: HTMLAttributes;
			ol: HTMLAttributes & {
				reversed?: boolean;
				start?: number;
				type?: string;
			};
			li: HTMLAttributes & { value?: number };
			dl: HTMLAttributes;
			dt: HTMLAttributes;
			dd: HTMLAttributes;
			menu: HTMLAttributes & { type?: string };
			figure: HTMLAttributes;
			figcaption: HTMLAttributes;
			blockquote: HTMLAttributes & { cite?: string };
			pre: HTMLAttributes;
			hr: HTMLAttributes;
			a: HTMLAttributes & {
				href?: string;
				target?: string;
				rel?: string;
				download?: string;
				hreflang?: string;
				ping?: string;
				referrerpolicy?: string;
			};
			b: HTMLAttributes;
			i: HTMLAttributes;
			strong: HTMLAttributes;
			em: HTMLAttributes;
			abbr: HTMLAttributes & { title?: string };
			cite: HTMLAttributes;
			code: HTMLAttributes;
			data: HTMLAttributes & { value?: string };
			dfn: HTMLAttributes;
			kbd: HTMLAttributes;
			mark: HTMLAttributes;
			q: HTMLAttributes & { cite?: string };
			rp: HTMLAttributes;
			rt: HTMLAttributes;
			ruby: HTMLAttributes;
			s: HTMLAttributes;
			samp: HTMLAttributes;
			small: HTMLAttributes;
			sub: HTMLAttributes;
			sup: HTMLAttributes;
			time: HTMLAttributes & { datetime?: string };
			u: HTMLAttributes;
			var: HTMLAttributes;
			wbr: HTMLAttributes;
			bdi: HTMLAttributes;
			bdo: HTMLAttributes;
			br: HTMLAttributes;
			del: HTMLAttributes & { cite?: string; datetime?: string };
			ins: HTMLAttributes & { cite?: string; datetime?: string };
			form: HTMLAttributes & {
				action?: string;
				method?: string;
				enctype?: string;
				acceptCharset?: string;
				autocomplete?: string;
				novalidate?: boolean;
				target?: string;
			};
			input: HTMLAttributes & {
				type?: string;
				name?: string;
				value?: string | Ref<string>;
				placeholder?: string;
				required?: boolean;
				checked?: boolean | Ref<boolean>;
				disabled?: boolean;
				readonly?: boolean;
				maxlength?: number;
				minlength?: number;
				min?: number | string;
				max?: number | string;
				step?: number | string;
				pattern?: string;
				size?: number;
				autocomplete?: string;
				autofocus?: boolean;
				multiple?: boolean;
				list?: string;
				accept?: string;
				capture?: string;
				alt?: string;
				height?: number | string;
				width?: number | string;
				src?: string;
			};
			button: HTMLAttributes & {
				type?: "button" | "submit" | "reset";
				name?: string;
				value?: string;
				disabled?: boolean;
				form?: string;
				formaction?: string;
				formenctype?: string;
				formmethod?: string;
				formnovalidate?: boolean;
				formtarget?: string;
			};
			select: HTMLAttributes & {
				name?: string;
				value?: string | Ref<string>;
				multiple?: boolean;
				size?: number;
				required?: boolean;
				disabled?: boolean;
			};
			option: HTMLAttributes & {
				value?: string;
				selected?: boolean;
				disabled?: boolean;
				label?: string;
			};
			optgroup: HTMLAttributes & {
				label?: string;
				disabled?: boolean;
			};
			textarea: HTMLAttributes & {
				name?: string;
				value?: string | Ref<string>;
				placeholder?: string;
				required?: boolean;
				disabled?: boolean;
				readonly?: boolean;
				rows?: number;
				cols?: number;
				maxlength?: number;
				minlength?: number;
				wrap?: "hard" | "soft" | "off";
			};
			label: HTMLAttributes & { for?: string };
			fieldset: HTMLAttributes & { name?: string; disabled?: boolean };
			legend: HTMLAttributes;
			datalist: HTMLAttributes;
			output: HTMLAttributes & { for?: string; name?: string };
			meter: HTMLAttributes & {
				value?: number;
				min?: number;
				max?: number;
				low?: number;
				high?: number;
				optimum?: number;
			};
			progress: HTMLAttributes & { value?: number; max?: number };
			table: HTMLAttributes;
			caption: HTMLAttributes;
			thead: HTMLAttributes;
			tbody: HTMLAttributes;
			tfoot: HTMLAttributes;
			tr: HTMLAttributes;
			th: HTMLAttributes & {
				scope?: "col" | "row" | "rowgroup" | "colgroup";
				colspan?: number;
				rowspan?: number;
				headers?: string;
			};
			td: HTMLAttributes & {
				colspan?: number;
				rowspan?: number;
				headers?: string;
			};
			colgroup: HTMLAttributes & { span?: number };
			col: HTMLAttributes & { span?: number };
			img: HTMLAttributes & {
				src?: string;
				alt?: string;
				width?: number | string;
				height?: number | string;
				srcset?: string;
				sizes?: string;
				loading?: "lazy" | "eager";
				decoding?: "async" | "auto" | "sync";
				crossorigin?: string;
				usemap?: string;
				ismap?: boolean;
				referrerpolicy?: string;
			};
			picture: HTMLAttributes;
			source: HTMLAttributes & {
				src?: string;
				srcset?: string;
				sizes?: string;
				type?: string;
				media?: string;
			};
			video: HTMLAttributes & {
				src?: string;
				controls?: boolean;
				autoplay?: boolean;
				loop?: boolean;
				muted?: boolean;
				poster?: string;
				preload?: "none" | "metadata" | "auto";
				width?: number | string;
				height?: number | string;
				playsinline?: boolean;
				crossorigin?: string;
			};
			audio: HTMLAttributes & {
				src?: string;
				controls?: boolean;
				autoplay?: boolean;
				loop?: boolean;
				muted?: boolean;
				preload?: "none" | "metadata" | "auto";
				crossorigin?: string;
			};
			track: HTMLAttributes & {
				src?: string;
				kind?: string;
				srclang?: string;
				label?: string;
				default?: boolean;
			};
			canvas: HTMLAttributes & {
				width?: number | string;
				height?: number | string;
			};
			map: HTMLAttributes & { name?: string };
			area: HTMLAttributes & {
				alt?: string;
				coords?: string;
				shape?: string;
				href?: string;
				target?: string;
				download?: string;
				rel?: string;
			};
			iframe: HTMLAttributes & {
				src?: string;
				srcdoc?: string;
				width?: number | string;
				height?: number | string;
				allow?: string;
				sandbox?: string;
				loading?: "lazy" | "eager";
				referrerpolicy?: string;
			};
			embed: HTMLAttributes & {
				src?: string;
				type?: string;
				width?: number | string;
				height?: number | string;
			};
			object: HTMLAttributes & {
				data?: string;
				type?: string;
				width?: number | string;
				height?: number | string;
				name?: string;
				usemap?: string;
			};
			param: HTMLAttributes & { name?: string; value?: string };
			details: HTMLAttributes & { open?: boolean };
			summary: HTMLAttributes;
			dialog: HTMLAttributes & { open?: boolean };
			script: HTMLAttributes & {
				src?: string;
				type?: string;
				async?: boolean;
				defer?: boolean;
				crossorigin?: string;
				integrity?: string;
				nomodule?: boolean;
			};
			noscript: HTMLAttributes;
			template: HTMLAttributes;
			slot: HTMLAttributes & { name?: string };
			style: HTMLAttributes & { type?: string; media?: string };
			link: HTMLAttributes & {
				rel?: string;
				href?: string;
				type?: string;
				as?: string;
				crossorigin?: string;
				integrity?: string;
				media?: string;
				sizes?: string;
				referrerpolicy?: string;
			};
			meta: HTMLAttributes & {
				name?: string;
				content?: string;
				charset?: string;
				"http-equiv"?: string;
			};
			svg: HTMLAttributes & {
				width?: number | string;
				height?: number | string;
				viewBox?: string;
				fill?: string;
				xmlns?: string;
				preserveAspectRatio?: string;
			};
			path: HTMLAttributes & {
				d?: string;
				fill?: string;
				stroke?: string;
				strokeWidth?: number | string;
				fillRule?: string;
				clipRule?: string;
			};
			circle: HTMLAttributes & {
				cx?: number | string;
				cy?: number | string;
				r?: number | string;
				fill?: string;
				stroke?: string;
				strokeWidth?: number | string;
			};
			rect: HTMLAttributes & {
				x?: number | string;
				y?: number | string;
				width?: number | string;
				height?: number | string;
				rx?: number | string;
				ry?: number | string;
				fill?: string;
				stroke?: string;
			};
			ellipse: HTMLAttributes & {
				cx?: number | string;
				cy?: number | string;
				rx?: number | string;
				ry?: number | string;
				fill?: string;
				stroke?: string;
			};
			line: HTMLAttributes & {
				x1?: number | string;
				y1?: number | string;
				x2?: number | string;
				y2?: number | string;
				stroke?: string;
				strokeWidth?: number | string;
			};
			polyline: HTMLAttributes & {
				points?: string;
				fill?: string;
				stroke?: string;
			};
			polygon: HTMLAttributes & {
				points?: string;
				fill?: string;
				stroke?: string;
			};
			text: HTMLAttributes & {
				x?: number | string;
				y?: number | string;
				fill?: string;
				fontSize?: number | string;
				fontFamily?: string;
				textAnchor?: string;
			};
			tspan: HTMLAttributes;
			g: HTMLAttributes;
			defs: HTMLAttributes;
			use: HTMLAttributes & { href?: string; xlinkHref?: string };
			symbol: HTMLAttributes & { id?: string; viewBox?: string };
			clipPath: HTMLAttributes & { id?: string };
			mask: HTMLAttributes & { id?: string };
			linearGradient: HTMLAttributes & {
				id?: string;
				x1?: string;
				y1?: string;
				x2?: string;
				y2?: string;
			};
			radialGradient: HTMLAttributes & {
				id?: string;
				cx?: string;
				cy?: string;
				r?: string;
			};
			stop: HTMLAttributes & {
				offset?: string;
				"stop-color"?: string;
				"stop-opacity"?: number | string;
			};
			math: HTMLAttributes;
		}
	}
}
